name: SignChestShop
main: co.technius.signchestshop.SignChestShopPlugin
version: 1.3.13
author: obnoxint
authors: [Technius]
depend: [Vault,NyaaUtils]
commands:
    signchestshop:
         description: SignChestShop commands
         usage: /signchestshop <args>
         aliases: [scs]
permissions:
    scs.admin:
        description: Grants access to administrative SignChestShop commands
        children:
            scs.bypass.*: true
    scs.bypass.*:
        description: Grants all bypass permissions
        children:
            scs.bypass.storage: true
            scs.bypass.edit: true
            scs.bypass.break: true
            scs.bypass.settitle: true
            scs.bypass.setmode: true
            scs.bypass.price: true